dist: xenial
language: python
sudo: false
cache: pip
env:
  global:
    MOZ_HEADLESS=1
  matrix:
  - TOXENV=py27-dj111
  - TOXENV=py36-dj111
  - TOXENV=py36-dj21
  - TOXENV=py35-dj22
  - TOXENV=py36-dj22
  - TOXENV=py37-dj22
  - TOXENV=py36-djdev
  - TOXENV=py37-djdev
matrix:
  allow_failures:
    - env: TOXENV=py36-djdev
    - env: TOXENV=py37-djdev
install:
  - pip install tox codecov

script:
  - tox -v

after_success:
  #- coverage combine
  - codecov
